### ISSUE TITLE
Overriding CSS

### ISSUE THREAD

**Issue by kerembeyazit** [fakhir-shad/react-character-counter#1]
When i added the `characterCounterStyle` prop, am getting an error.

`TypeError: Cannot assign to read only property 'color' of object '#<Object>'`

**Comment by fakhir-shad** [comment]
Can you share your code please?

**Comment by kerembeyazit** [comment]
I used your sample;

```
<CharacterCounter
  value={this.state.name}
  maxLength={120}
  wrapperStyle={{position: 'relative'}}
  characterCounterStyle={{
    position: "absolute",
    fontSize: "12px",
    fontWeight: "600",
    top: "14px",
    right: "0px"
  }}
>
  <input type='text' maxLength={120}  value={this.state.name}>
</CharacterCounter>
```

React: 16.10.2

**Comment by fakhir-shad** [comment]
I tried the above example and it is working fine. I think it might be related to your codebase, as you can see there is no 'color' prop in the above example.

**Comment by kerembeyazit** [comment]
I will try again, thanks your help.
